document.write(""
+"<form method=\"post\" action=\"@tradedoubler.form.action@\">"
+"<div style=\"width: 178px; height: 65px; margin: 0px 0px 0px; background: url('@tradedoubler.context.url@tradedoubler/searchbox/bg-65.png'); border-left: 1px solid #bfc0c4; border-right: 1px solid #bfc0c4;\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"7\"/>"
+"<div style=\"padding-top: 2px; padding-left: 2px;\">"
+"<input type=\"radio\" name=\"td_c\" value=\"d\" style=\"margin-left: 5px;\" checked=\"checked\">Norge"
+"<input type=\"radio\" name=\"td_c\" value=\"p\" style=\"margin-left: 8px;\">Bilder"
+"</div>"
+"<input type=\"text\" name=\"td_q\" size=\"20\" style=\"height: 20px; width: 170px; margin-left: 4px; border: 1px solid #bcc5cc;\"/>"
+"<br/>"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-star.png\" style=\"float: right; padding-top: 2px; padding-right: 4px;\" />"
+"</div>"
+"</form>"
);
