document.write(""
+"<form method=\"post\" action=\"@tradedoubler.form.action@\">"
+"<div style=\"width: 466px; height: 60px; margin: 0px 0px 0px 0px; background: url('@tradedoubler.context.url@tradedoubler/searchbox/bg.png'); border-left: 1px solid #bfc0c4; border-right: 1px solid #bfc0c4;\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"1\"/>"
+"<table>"
+"<tr><td style=\"padding-top: 8px;\">"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/logo-big.png\" alt=\"\" style=\"padding-bottom: 1px; padding-left: 5px;\"/>"
+"</td><td style=\"padding-top: 8px;\">"
+"<input type=\"text\" name=\"td_q\" size=\"35\" style=\"height: 24px; border: 1px solid #bcc5cc; width: 315px;\"/>"
+"</td><td style=\"padding-top: 8px;\">"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-white.png\" style=\"\" />"
+"</td></tr>"
+"<tr><td colspan=\"3\" style=\"padding-top: 0px; margin-top: 0px; padding-bottom: 3px;\">"
+"<div style=\"padding-top: 0px; margin-top: 0px;\">"
+"<input type=\"radio\" name=\"td_c\" value=\"m\" checked=\"checked\" style=\"margin-left: 90px;\">Nyheter"
+"<input type=\"radio\" name=\"td_c\" value=\"d\" style=\"margin-left: 20px;\">Norge"
+"</td></tr>"
+"</table>"
+"</div>"
+"</form>"
);
