document.write(""
+"<div style=\"height: 60px;\">"
+"<script type=\"text/javascript\" language=\"JavaScript\">"
+"function toggleMenu(show){"
+"var obj = document.getElementById('search_menu');"
+""
+"if (show == true){"
+"var sbm = document.getElementById('submit_img');"
+"obj.style.top = (sbm.offsetTop + sbm.offsetHeight) + \"px\";"
+"obj.style.left= (sbm.offsetLeft - 1) + \"px\";"
+"obj.style.display='block';"
+"setTimeout('toggleMenu(false)', 3000);"
+"} else {"
+"obj.style.display='none';"
+"}"
+"}"
+""
+"function chooseSearch(key){"
+"var sbm = document.getElementById('submit_img');"
+"var contextobj = document.getElementById('contextobject');"
+"var baseurl = '@tradedoubler.context.url@tradedoubler/searchbox';"
+""
+"if (key == 'd'){"
+"contextobj.setAttribute('value', key);"
+"sbm.src = baseurl + \"/button-sesam-long.png\";"
+"} else if (key == 'y'){"
+"contextobj.setAttribute('value', key);"
+"sbm.src = baseurl + \"/button-company.png\";"
+"} else if (key == 'w'){"
+"contextobj.setAttribute('value', key);"
+"sbm.src = baseurl + \"/button-person.png\"; "
+"}"
+"toggleMenu(false);"
+"return true;"
+"}"
+"</script>"
+"<form style=\"position: absolute;\" method=\"post\" action=\"@tradedoubler.form.action@\">"
+"<div style=\"width: 466px; height: 60px; margin: 0px 0px 0px 0px; background: url('@tradedoubler.context.url@tradedoubler/searchbox/bg.png'); border-left: 1px solid #bfc0c4; border-right: 1px solid #bfc0c4;\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"6\"/>"
+"<input type=\"hidden\" id=\"contextobject\" name=\"td_c\" value=\"d\"/>"
+"<div style=\"position: absolute; top: 0px; left: 0px;\">"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/logo-big.png\" alt=\"\" style=\"position: absolute; top: 15px; left: 10px;\"/>"
+"<input type=\"text\" name=\"td_q\" size=\"30\" style=\"position: absolute; top: 17px; left: 100px; width: 266px; border: 1px solid #bcc5cc; height: 24px; \"/>"
+"<input type=\"image\" id=\"submit_img\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-sesam-long.png\" "
+"style=\"position: absolute; top: 17px; left: 366px;\" />"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/down-arrow.png\" alt=\"\" "
+"style=\"position: absolute; top: 17px; left: 437px;\" onmousedown=\"javascript:toggleMenu(true);\"/>"
+"</div>"
+"<div id=\"search_menu\" style=\"display: none; background: #bcc5cc; width: 71px; height: 72px; position: absolute; top: 0px; left: 0px; border-left: 1px solid #bcc5cc;\">"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-sesam-long.png\" alt=\"\" style=\"\""
+"onclick=\"javascript:chooseSearch('d');\"/><br/>"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-company.png\" alt=\"\" style=\"\""
+"onclick=\"javascript:chooseSearch('y');\"/><br/>"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-person.png\" alt=\"\" style=\"\""
+"onclick=\"javascript:chooseSearch('w');\"/>"
+"</div>"
+"</div>"
+"</form>"
+"</div>"
);
