document.write(""
+"<div style=\"height: 60px; width: 468px; margin-top: 0px; padding-top: 0px;\">"
+"<form method=\"post\" action=\"@tradedoubler.form.action@\" style=\"margin-top: 0px; padding-top: 0px; height: 58px; width: 466px;\">"
+"<div style=\"position: absolute; width: 466px; height: 58px; margin: 0px 0px 0px 0px; background: #ae208e; border: 1px solid #bfc0c4;\">"
+"<div style=\"position: absolute; top: 0px; left: 0px; width: 91px; height: 58px; background: #bfc0c4; border-width: 0px;\">"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/logo-border.png\" alt=\"\" style=\"border: 0px solid #bfc0c4; background: #bfc0c4; height: 58px;\"/>"
+"</div>"
+"<div style=\"position: absolute; top: 8px; left: 91px;\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"3\"/>"
+"<input type=\"text\" name=\"td_q\" size=\"35\" style=\"width: 290px; margin-left: 10px; border: 1px solid #bcc4cf; height: 24px;\"/>"
+"</div>"
+"<div style=\"position: absolute; top: 8px; left: 395px;\">"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-sesam.png\" style=\"margin-top: 0px; padding-top: 0px; padding-right: 15px;\" />"
+"</div>"
+"<div style=\"position: absolute; top: 37px; left: 100px;\">"
+"<input type=\"radio\" name=\"td_c\" value=\"m\" checked=\"checked\" style=\"margin-left: 15px;\">Nyheter"
+"<input type=\"radio\" name=\"td_c\" value=\"d\" style=\"margin-left: 20px;\">Norge"
+"</div>"
+"</div>"
+"</form>"
+"</div>"
);
