document.write(""
+"<div style=\"width: 180px; height: 118px;\">"
+"<div style=\"position: absolute; width: 178px; height: 118px; margin: 0px 0px 0px 0px; background: url('@tradedoubler.context.url@tradedoubler/searchbox/bg-118.png'); border-left: 1px solid #bfc0c4; border-right: 1px solid #bfc0c4;\">"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/logo-65.png\" alt=\"\" style=\"position: absolute; left: 6px; top: 3px; padding-bottom: 3px;\"/>"
+"<br/>"
+"<form method=\"post\" action=\"@tradedoubler.form.action@\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"5\"/>"
+"<input type=\"hidden\" name=\"td_c\" value=\"y\"/>"
+""
+"<input type=\"text\" name=\"td_q\" size=\"11\" style=\"position: absolute; top: 20px; left: 5px; border: 1px solid #bcc5cc; height: 24px; width: 90px; \"/>"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-company.png\" style=\"position: absolute; top: 20px; left: 95px;\"/>"
+"</form>"
+"<form method=\"post\" action=\"@tradedoubler.form.action@\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"5\"/>"
+"<input type=\"hidden\" name=\"td_c\" value=\"w\"/>"
+""
+"<input type=\"text\" name=\"td_q\" size=\"11\" style=\"position: absolute; top: 50px; left: 5px; border: 1px solid #bcc5cc; height: 24px; width: 90px; \"/>"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-person.png\" style=\"position: absolute; top: 50px; left: 95px;\"/>"
+"</form>"
+"<form method=\"post\" action=\"@tradedoubler.form.action@\">"
+"<input type=\"hidden\" name=\"td_lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"td_alt\" value=\"5\"/>"
+"<input type=\"hidden\" name=\"td_c\" value=\"d\"/>"
+""
+"<input type=\"text\" name=\"td_q\" size=\"11\" style=\"position: absolute; top: 79px; left: 5px; border: 1px solid #bcc5cc; height: 24px; width: 90px;\"/>"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-sesam-long.png\" style=\"position: absolute; top: 79px; left: 95px;\"/>"
+"</form>"
+"</div>"
+"</div>"
);
