document.write(""
+"<div style=\"height: 65px; width: 180px;\">"
+"<form method=\"get\" action=\"@searchbox.form.action@\">"
+"<div style=\"width: 180px; height: 65px; margin: 0px 0px 0px 0px; background: url('@tradedoubler.context.url@tradedoubler/searchbox/bg-65.png'); border-right: 1px solid #bfc0c4; border-left: 1px solid #bfc0c4;\">"
+"<input type=\"hidden\" name=\"lang\" value=\"en\"/>"
+"<input type=\"hidden\" name=\"ss_lt\" value=\"searchbox\"/>"
+"<input type=\"hidden\" name=\"ss_ss\" value=\"intra\"/>"
+"<input type=\"hidden\" name=\"ss_sec\" value=\"5\"/>"
+"<img src=\"@tradedoubler.context.url@tradedoubler/searchbox/logo-65.png\" alt=\"\" style=\"margin-left: 5px; padding-top: 3px; padding-bottom: 1px;\"/>"
+"<br/>"
+"<input type=\"text\" name=\"q\" size=\"13\" style=\"float: left; margin-left: 5px; border: 1px solid #bcc5cc; height: 24px; margin-right: 0px; padding-right: 0px;\"/>"
+"<input type=\"image\" src=\"@tradedoubler.context.url@tradedoubler/searchbox/button-yellow.png\" style=\"padding-right: 7px; padding-bottom: 2px;\" />"
+"<div>"
+"<input type=\"radio\" name=\"c\" value=\"y\" style=\"margin-left: 6px;\" checked=\"checked\">Bedrift"
+"<input type=\"radio\" name=\"c\" value=\"w\" style=\"margin-left: 8px;\">Person"
+"</div>"
+"</div>"
+"</form>"
+"</div>"
);
