document.write('<div id="sesamsok" style="background:url(http://www.sesam.no/export/pss/tradebg_468x50.jpg) no-repeat; height:50px; width:468px; position:relative; text-align:left; font:11px Arial, Helvetica, sans-serif; color:#686663; line-height:1em;">');
document.write('  <form name="search" action="http://sesam.no/search/" method="get" >');
document.write('  <div>');
document.write('    <input type="text" name="q" style="width:336px; position:absolute; left:10px; top:5px; padding:1px 0 1px 3px; font-weight:bold;" />');
document.write('    <input name="ss_lt" value="searchbox" type="hidden"/>');
document.write('    <input name="ss_ss" value="' + location.host + '" type="hidden"/>');
document.write('    <input name="ss_pid" value="sesamvenn" type="hidden"/>');
document.write('    <input name="sitesearch" value="' + location.host + '" type="hidden"/>');
document.write('    <input type="image" style="position:absolute; left:360px; top:6px;" value="submit" src="http://www.sesam.no/export/pss/sokButtonsmall.gif" alt="S&oslash;k" />');
document.write('  </div>');
document.write('  <div>');
document.write('    <ul style="list-style:none; padding: 27px 0px 0px 6px; margin:0; font-weight:bold; color:#87005B;">');
document.write('	<li style="display:inline; padding:0 5px 0 0; margin:0;"><label><input type="radio" name="c" value="pss" checked="checked" />');
document.write(location.host);
document.write('</label></li>');
document.write('	<li style="display:inline; padding:0; margin:0;"><label><input type="radio" name="c" value="d" /> Netts&oslash;k</label></li>');
document.write('    </ul>');
document.write('  </div>');
document.write('  </form>');
document.write('</div>');