document.write('<div id="sesamsok" style="width:768px; height:35px; background-image:url(http://www.sesam.no/export/tradedoubler/tradebg_768x35.jpg); background-color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#686663; margin:2px 0px 0px 0px; line-height:10px;">');
document.write('<table width="670" height="30" border="0" cellspacing="0" cellpadding="0" style="margin:0px 0px 0px 7px;">');
document.write('<form name="input" action="http://www.sesam.no/search/" method="get" style="margin:2px 0px 0px 0px;"><tr>');
document.write('<td width="130"><div align="left"><img src="http://www.sesam.no/export/tradedoubler/ikonNorske.jpg" alt="" align="absmiddle"/>');
document.write('<input type="radio" name="c" value="d" checked="checked" style="vertical-align:middle;">');
document.write('<span style="color:#87005B; vertical-align:middle;"><b>NORSKE SØK</b></td>');
document.write('<td width="122"><img src="http://www.sesam.no/export/tradedoubler/ikonPrivat.jpg" alt="" align="absmiddle" />');
document.write('<input type="radio" name="c" value="w" style="vertical-align:middle;"><span style="color:#87005B; vertical-align:middle;"><b>Personsøk</b></span></td>');
document.write('<td width="114"><img src="http://www.sesam.no/export/tradedoubler/ikonBedrift.jpg" alt="" align="absmiddle" />');
document.write('<input type="radio" name="c" value="y" style="vertical-align:middle;"><span style="color:#87005B; vertical-align:middle;"><b>Bedriftsøk</b></span></td>');
document.write('<td width="241" rowspan="2"><input type="text" name="q" style="width:220px; margin:4px 0px 0px 5px;"></td>');
document.write('<td width="51" rowspan="2"><input type="image" name="" value="" src="http://www.sesam.no/export/tradedoubler/sokButtonsmall.gif" alt="Submit" width="45" height="18" border="0" style="margin:4px 0px 0px 0px; "/></td>');
document.write('</tr>');
document.write('</form>');
document.write('<tr>');
document.write('<td><span><span style="font-size:10px; margin-left:20px;">søk på nummer:</span></td>');
document.write('<td><span style="font-size:10px; margin-left:20px;">søk på nummer:</span></td>');
document.write('<td><span style="font-size:10px; margin-left:20px;">søk på nummer:</span></td>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
