document.write('<div id="sesamsok" style="width:100px; height:120px; background-image:url(http://www.sesam.no/export/tradedoubler/intranetbg_100x120.jpg); background-color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#686663; margin:0px 0px 0px 0px; line-height:11px;">');
document.write('<table width="93" height="114" border="0" cellspacing="0" cellpadding="0" style="margin:2px 0 0 7px;">');
document.write('<form name="input" action="http://www.sesam.no/search/" method="get" style="margin:0px 0px 0px 7px;">');
document.write('<tr>');
document.write('<td colspan="2"><span style="color:#87005B; margin-top:2px;">NORSKE SØK</span><br /><span style="font-size:10px;">søk på nummer:</span></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="text" name="q" style="width:80px; margin:0px 0 1px 0;"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="image" name="" value="" src="http://www.sesam.no/export/tradedoubler/sokButton.gif" width="85" height="18" border="0" alt="Submit"";"/></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td width="15"><img src="http://www.sesam.no/export/tradedoubler/ikonPrivat.jpg" alt="" /></td>');
document.write('<td width="72"><input type="radio" name="c" value="w" checked="checked">Tlf Privat</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td><img src="http://www.sesam.no/export/tradedoubler/ikonBedrift.jpg" alt="" /></td>');
document.write('<td><input type="radio" name="c" value="y">Tlf Bedrift</td>');
document.write('</form>');
document.write('</tr>');
document.write('<tr>');
document.write('<td>&nbsp;</td>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
