document.write('<div id="sesamsok" style="width: 150px; height: 120px; background-image:url(http://www.sesam.no/export/tradedoubler/tradedoublerbg_150x120.gif); background-color:#FFFFFF; font-family:Arial, Helvetica, sans-serif; font-size: 11px; color: #686663; margin: 0px 0px 0px 0px; line-height: 10px;">');
document.write('<table width="143" heigth="120" border="0" cellspacing="0" cellpadding="0" style="margin:0 0 0 7px;">');
document.write('<form name="input" action="http://www.sesam.no/search/" method="get" style="margin:0px 0px 0px 7px;">');
document.write('<tr>');
document.write('<td height="20" colspan="2"><input type="radio" name="c" value="w" checked="checked">Person<input type="radio" name="c" value="y">Bedrift</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height="26"><input type="text" name="q" style="width:80px; margin:1px 0 1px 0;"><input type="image" name="" value="" src="http://www.sesam.no/export/tradedoubler/button_sok_small.gif" width="45" height="18" border="0" alt="Submit" style="margin-top:5px; margin-left:2px; "></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height="13"><span style="font-size:12px; color:#87005b; font-weight: bold;">NORSKE S&Oslash;K </span></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height="22"><span style="font-size:10px;">Du kan s&oslash;ke p&aring; navn, telefon-<br>nummer, sted, bransje osv.</span> </td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height="18"><img src="http://www.sesam.no/export/tradedoubler/ikon_bildesok.gif" width="15" height="15" align="absbottom" style="margin:0px 3px 0px 0px;" /><a href="http://www.sesam.no/search/?c=p&q=" style="color:#7568AD; text-decoration:none; "><b>Prøv også Bildesøk</b></a></span></td>');
document.write('</form>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
