document.write('<div id="sesamsok" style="width: 180px; height: 170px; background-image:url(http://www.sesam.no/export/tradedoubler/tradedoublerbg_180x170.gif); background-color:#FFFFFF; font-family:Arial, Helvetica, sans-serif; font-size: 10px; color: #686663; margin: 0px 0px 0px 0px; line-height: 10px;">');
document.write('<table width="173" height="150" border="0" cellspacing="0" cellpadding="0" style="margin:0 0 0 7px; vertical-align: top;">');
document.write('<form name="input" action="http://www.sesam.no/search/?c=d&" method="get" style="margin:0px 0px 0px 7px;">');
document.write('<tr>');
document.write('<td height="18"><img src="http://www.sesam.no/export/tradedoubler/ikon_sesamsok.gif" width="12" height="12" style="margin:6px 3px 0px 0px;"/></td>');
document.write('<td height="18" valign="bottom"><span style="font-size:11px; color:#87005b; font-weight: bold;">Norske søk.</span> Kom til saken.</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="text" name="q" style="width:115px; margin:1px 0 1px 0;"><input type="image" name="" src="http://www.sesam.no/export/tradedoubler/button_sok_small.gif" width="45" height="18" border="0" alt="Submit" style="margin-top:5px; margin-left:2px; "></td>');
document.write('</tr>');
document.write('</form>');
document.write('<form name="input" action="http://www.sesam.no/search/" method="get">');
document.write('<tr>');
document.write('<td height="22" valign="top"><img src="http://www.sesam.no/export/tradedoubler/ikon_bedrift2.gif" width="12" height="12" style="margin:2px 3px 0px 0px;"/></td>');
document.write('<td valign="bottom"><span style="font-size:11px; color:#87005b; font-weight: bold;">Personsøk. </span>Søk på navn, telefonnummer, sted osv.</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="text" name="q" style="width:115px; margin:1px 0 1px 0;"><input type="hidden" name="c" value="w"><input type="image" name="" src="http://www.sesam.no/export/tradedoubler/button_sok_small.gif" width="45" height="18" border="0" alt="Submit" style="margin-top:5px; margin-left:2px; "></td>');
document.write('</tr>');
document.write('</form>');
document.write('<form name="input" action="http://www.sesam.no/search/?c=y&" method="get">');
document.write('<tr>');
document.write('<td height="22" valign="top"><img src="http://www.sesam.no/export/tradedoubler/ikon_privat2.gif" width="12" height="11" style="margin:2px 3px 0px 0px;"/></td>');
document.write('<td height="20" valign="bottom"><span style="font-size:11px; color:#87005b; font-weight: bold;">Bedriftsøk. </span>Søk på firma, adresse, telefonnummer osv.</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="text" name="q" style="width:115px; margin:1px 0 1px 0;"><input type="hidden" name="c" value="y"><input type="image" name="" src="http://www.sesam.no/export/tradedoubler/button_sok_small.gif" width="45" height="18" border="0" alt="Submit" style="margin-top:5px; margin-left:2px; "></td>');
document.write('</tr>');
document.write('</form>');
document.write('</table>');
document.write('</div>');
