document.write('<form name="tipsform" method="get" action="http://www.sesam.no/psearch/">');
document.write('<input name="lan" value="en" type="hidden" />');
document.write('<input name="ss_lt" value="searchbox" type="hidden"/>');
document.write('<input name="ss_ss" value="' + location.host + '" type="hidden"/>');
document.write('<input name="ss_pid" value="sesamvenn" type="hidden"/>');
document.write('<table border="0" cellpadding="0" cellspacing="0" style="width: 178px; height: 83px; margin:5px 0px; background: #F3F3F3; border: 1px solid #A63F83;">');
document.write('<tr><td valign="middle" style="padding-left:5px;"><img src="http://www.sesam.no/export/js/logo.gif" alt="logo" /></td></tr>');
document.write('<tr>');
document.write('<td width="120">');
document.write('<select name="c" style="margin-left: 5px;">');
document.write('<option value="d">Sesams&#248;k</option>');
document.write('<option value="m">Nyhetss&#248;k</option>');
document.write('<option value="y">Bedriftss&#248;k&nbsp;&nbsp;&nbsp;&nbsp;</option>');
document.write('<option value="w">Persons&#248;k</option>');
document.write('<option value="p">Bildes&#248;k</option>');
document.write('</select>');
document.write('</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td width="120"><input type="text" name="q" size="14" style="margin:0px 5px;" /></td>');
document.write('<td width="58"><input type="image" src="http://www.sesam.no/export/js/s_button.gif" /></td>');
document.write('</tr>');
document.write('</table>');
document.write('</form>');