document.write('<div id="sesamsok" style="width:100px; height:120px; background-image:url(http://www.sesam.no/export/intranett/intranetbg_100x120.jpg); background-color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#686663; margin:0px 0px 0px 0px; line-height:10px;">');
document.write('<table width="93" height="105" border="0" cellspacing="0" cellpadding="0" style="margin:0 0 0 7px;">');
document.write('<form name="input" action="http://www.sesam.no/search/" method="get" style="margin:0px 0px 0px 7px;">');
document.write('<tr>');
document.write('<td width="15"><img src="http://www.sesam.no/export/intranett/ikonPrivat.jpg" alt="" /></td>');
document.write('<td width="72"><input type="radio" name="c" value="w" checked="checked">Tlf Privat</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td><img src="http://www.sesam.no/export/intranett/ikonBedrift.jpg" alt="" />');
document.write('<input name="ss_lt" value="searchbox" type="hidden"/>');
document.write('<input name="ss_ss" value="' + location.host + '" type="hidden"/>');
document.write('<input name="ss_pid" value="sesamvenn" type="hidden"/>');
document.write('</td>');
document.write('<td><input type="radio" name="c" value="y">Tlf Bedrift</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="text" name="q" style="width:80px; margin:0px 0 1px 0;"></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><input type="image" name="" value="" src="http://www.sesam.no/export/intranett/sokButton.gif" width="85" height="18" border="0" alt="Submit" style="margin-top:1px; margin-bottom:2px; "/></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><span style="font-size:10px; text-align:center;">&nbsp;S&#248;k p&#229; navn, nr, &nbsp;sted, bransje osv.</span></td>');
document.write('</form>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
