document.write('<div id="sesamsok" style="width:150px; height:110px; background-image:url(http://www.sesam.no/export/intranett/intranetbg_150x110.jpg); background-color:#000000; font-family:Arial, Helvetica, sans-serif; font-size:11px; color:#686663; margin:0px 0px 0px 0px; line-height:10px;">');
document.write('<table width="143" height="90" border="0" cellspacing="0" cellpadding="0" style="margin:0 0 0 7px;">');
document.write('<form name="input" action="http://www.sesam.no/search/" method="get" style="margin:0px 0px 0px 7px;">');
document.write('<tr>');
document.write('<td height="22" colspan="2"><input type="radio" name="c" value="w" checked="checked">Person&nbsp;<input type="radio" name="c" value="y">Bedrift</td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height="26"><input type="text" name="q" style="width:85px; margin:1px 0 1px 0;"></td>');
document.write('<td><input type="image" name="" value="" src="http://www.sesam.no/export/intranett/sokButtonsmall.gif" width="45" height="18" border="0" alt="Submit" style="margin:1px 3px 2px 0; "/></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td height="22" colspan="2"><span style="font-size:10px; text-align:center;">Du kan søke på navn, telefon-<br/>nummer, sted, bransje osv.</span></td>');
document.write('</tr>');
document.write('<tr>');
document.write('<td colspan="2"><img src="http://www.sesam.no/export/intranett/ikonNyhet.jpg" alt="" width="15" height="15" align="absbottom" style="margin:0px 3px 0px 0;" /><span style="color:#7568AD; "><a href="http://www.sesam.no/search/?nav_sources=contentsourcenavigator&c=m&contentsource=Norske%20nyheter&userSortBy=datetime&q=" style="color:#7568AD; text-decoration:none;"><b>Prøv også Nyhetssøk</b></a></span></td>');
document.write('</form>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
