document.write('<form name="tipsform" method="get" action="http://www.sesam.no/psearch/">');
document.write('<input name="lan" value="en" type="hidden" />');
document.write('<input name="c" value="d" type="hidden" />');
document.write('<table border="0" cellpadding="0" cellspacing="0" style="width: 398px; height: 28px; margin:5px 0px; background: #F3F3F3; border: 1px solid #D1D1D1;">');
document.write('<tr>');
document.write('<td valign="middle" width="85"><img src="http://www.sesam.no/export/js/logo.gif" alt="logo" style="padding-left:5px;" /></td>');
document.write('<td width="215"><input type="text" name="q" size="32" /></td>');
document.write('<td width="98"><input type="image" src="http://www.sesam.no/export/js/l_button.gif" style="padding-left:5px;" /></td>');
document.write('</tr>');
document.write('</table>');
document.write('</form>');