document.write('<form name="tipsform" method="get" action="http://www.sesam.no/psearch/">');
document.write('<input name="lan" value="en" type="hidden" />');
document.write('<input name="ss_lt" value="searchbox" type="hidden"/>');
document.write('<input name="ss_ss" value="' + location.host + '" type="hidden"/>');
document.write('<input name="ss_pid" value="sesamvenn" type="hidden"/>');
document.write('<table border="0" cellpadding="0" cellspacing="0" style="width:466px; height:26px; margin:5px 0px; background: #F3F3F3; border: 1px solid #D1D1D1;">');
document.write('<tr>');
document.write('<td valign="middle" width="85"><img src="http://www.sesam.no/export/js/logo.gif" alt="logo" style="padding-left:5px;" /></td>');
document.write('<td width="105" style="height:20px;">');
document.write('<select name="c" style="height:20px;">');
document.write('<option value="d">Sesams&#248;k</option>');
document.write('<option value="m">Nyhetss&#248;k</option>');
document.write('<option value="y">Bedriftss&#248;k&nbsp;&nbsp;&nbsp;&nbsp;</option>');
document.write('<option value="w">Persons&#248;k</option>');
document.write('<option value="p">Bildes&#248;k</option>');
document.write('</select>');
document.write('</td>');
document.write('<td width="205"><input type="text" name="q" size="30" style="margin: 0px 5px;" /></td>');
document.write('<td width="71"><input type="image" src="http://www.sesam.no/export/js/s_button.gif" /></td>');
document.write('</tr>');
document.write('</table>');
document.write('</form>');